# Global data directory settings
storage:
  base_dir: "/Users/macbookair/Documents/GitHub/AdsMarketingCampaign/data/raw/"
  base_data: "/Users/macbookair/Documents/GitHub/AdsMarketingCampaign/data/raw/ads_campaign_data.csv"
  processed_dir: "/Users/macbookair/Documents/GitHub/AdsMarketingCampaign/data/processed/"
  processed_train_data: "/Users/macbookair/Documents/GitHub/AdsMarketingCampaign/data/processed/ads_campaign_data_train.csv"
  processed_test_data: "/Users/macbookair/Documents/GitHub/AdsMarketingCampaign/data/processed/ads_campaign_data_test.csv"
  feature_store_dir: "/Users/macbookair/Documents/GitHub/AdsMarketingCampaign/data/feature_store/"
  selected_dir: "/Users/macbookair/Documents/GitHub/AdsMarketingCampaign/data/selected/"

# Feature selection 
feature_selection:
  target_column: "Revenue"
  selected_features: ["Clicks_Plus_Leads", "Clicks", "Leads"]